module.exports = {
	PING: '/ping',

	PRODUCTBASEURL: '/products',
	CREATEPRODUCT: '/createProduct/',
	GETALLPRODUCTS: '/getAllProducts/',
	GETPRODUCTBYID: '/getProductById/:productId',
	DELETEPRODUCTBYID: '/deleteProductById/',
	UPDATEPRODUCTBYID: '/updateProduct/',
	GETACTIVEPRODUCTS: '/getActiveProducts/',
	GETPRODUCTDEFBYID: '/getProductDefById/:productId',
	GETPRODUCTSBYCATEGORYID: '/getProductsByCategoryId/:categoryId',
	GETPRODUCTLISTBYIDLIST: '/getProductListByProductIdsList',
	GETRECENTADDEDPRODUCTS: '/getRecentAddedProducts',
	GETPRODUCTSBYNAMEMATCHES: '/getProductsByProductNameMatch',
	GETNEWPRODUCTS: '/getNewProducts',
	GETTOTALPRODUCTSCOUNT: '/getTotalProductsCount',
	GETACTIVEPRODUCTSWITHFILTERS: '/getActiveProductsWithFilters',
	GETRANDOMPRODUCTS: '/getRandomProducts',
	GETRELATEDPRODUCTSBYCATEGORY: '/getRelatedProductsByCategory/:productId',

	GETPRODUCTFROMCSV: '/getProductsFromCSV',
	GETPRODUCTSEXPORTSHEET: '/downloadProductExportSheet',
	GETPRODUCTSIMPORTSHEET: '/downloadProductImportSheet',

	ATTRIBUTEBASEURL: '/attributes',
	GETALLATTRIBUTES: '/getAllAttributes',
	CREATEATTRIBUTE: '/createAttribute/',

	ATTRIBUTESETBASEURL: '/attributeset',
	GETALLATTRIBUTESET: '/getAllAttributeSets/',
	CREATEATTRIBUTESET: '/createAttributeSet/',
	DELETEATTRIBUTESETBYID: '/deleteAttributeSetById/',
	UPDATEATTRIBUTESETBYID: '/updateAttributeSetById/',

	CATEGORYBASEURL: '/categories',
	CREATECATEGORY: '/createCategory/',
	CREATEDEFAULTCATEGORY: '/createDefaultCategoryForClient/:clientId',
	GETALLCATEGORIES: '/getAllCategories/',
	GETATTRIBUTESBYCATEGORYID: '/getAttributesByCategoryId/:categoryId',
	DELETECATEGORYBYID: '/deleteCategoryById/',
	UPDATECATEGORYBYID: '/updatecategory/',

	CARTBASEURL: '/cart',
	ADDTOCART: '/addToCart/',
	UPDATECARTPRODUCTS: '/updateCartProducts/',
	REMOVEFROMCART: '/removeCartProduct/',
	REMOVELISTOFPRODUCTFROMCART: '/removeCartProducts',
	GETCART: '/getCart',
	GETCARTIDBYUSERID: '/getCartIdByUserId/:userId',
	REMOVEALLFROMCART: '/removeAllCartProduct',
	CLEARCARTANDADDPRODUCT: '/clearAndAddCartProduct',

	WISHLISTBASEURL: '/wishlist',
	ADDTOWISHLIST: '/addToWishlist',
	CREATEWISHLISTANDADDPRODUCT: '/createWishlistAndAddProduct',
	REMOVEFROMWISHLIST: '/removeWishlistProduct',
	GETWISHLIST: '/getWishlist',
	GETWISHLISTALLWISHLISTSBYUSERID: '/getAllWishlistsByUserId/:userId',
	REMOVEALLFROMWISHLIST: '/removeAllWishlistProduct',
	REMOVEALLWISHLISTSBYUSERID: '/removeAllWishlistByUserId',
	GETALLWISHLISTLISTNAMES: '/getAllWishlistListNamesByUserId',
	CREATEWISHLIST: '/createWishlist',
	UPDATEWISHLIST: '/updateWishlist/:wishlistId',
	DELETEWISHLIST: '/deleteWishlist/:wishlistId',

	CHECKOUTBASEURL: '/checkout',
	GETCHECKOUTBYID: '/getCheckoutById/:checkoutId',
	CREATECHECKOUT: '/createCheckout',
	CREATECHECKOUTFROMPREVIOUSORDER: '/createCheckoutFromPreviousOrder',
	CREATECHECKOUTFROMWISHLIST: '/createCheckoutFromWishlist',
	CREATECHECKOUTFROMPRODUCTLIST: '/createCheckoutFromProductList',
	ADDADDRESSANDSCHEDULEDDATE: '/addAddressAndScheduledDate',
	DELETECHECKOUTBYID: '/deleteCheckoutById/:checkoutId',
	GETPROFORMAINVOICE: '/getProformaInvoice/:checkoutId',
	REVERTCHECKOUT: '/revertCheckout/:checkoutId',

	DEALSBASEURL: '/deals',
	GETALLDEALS: '/getAllDeals',
	GETDEALBYDEALID: '/getDealByDealId/:dealId',
	CREATEDEAL: '/createDeal',
	UPDATEDEALBYID: '/updateDeal',
	DELETEDEALBYID: '/deleteDealById/:dealId',
	GETPRODUCTSWITHOUTDEAL: '/getAllProductsWithoutDeal',
	GETDEALPRODUCTS: '/getDealProducts',
	GETDEALPRODUCTSCOUNT: '/getDealProductsCount',
	GETALLONGOINGDEALS: '/getAllOngoingDeals',

	DEALDETAILBASEURL: '/dealDetail',
	GETALLDEALDETAILS: '/getAllDealDetails',
	GETDEALDETAILBYID: '/getDealDetailByDealDetailId/:dealDetailId',
	CREATEDEALDETAIL: '/createDealDetail',
	DELETEDEALDETAILBYID: '/deleteDealDetailByDealDetailId/:dealDetailId',
	UPDATEDEALDETAIL: '/updateDealDetail',

	HOMEBASEURL: '/asset',
	GETHOMEPAGEBANNERS: '/getHomeBanners',
	UPDATEHOMEBANNERS: '/updateHomeBanners',
	GETDEFAULTHOMEPAGEBANNERS: '/getDefaultHomeBanners',
	UPDATEDEFAULTHOMEBANNERS: '/updateDefaultHomeBanners',

	WITHOUTAUTH: '/publicRoute',
	UPDATEPRODUCTQTYONFAILEDCHECKOUT: '/updateProductQtyOnFailedCheckout',
};
